In [14]:
import numpy as np
import pandas as pd
import seaborn as sns
import pickle as pck
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [15]:

dataset = pd.read_csv('dataset_malwares.csv')

In [16]:
dataset.head()
from sklearn.model_selection import train_test_split

In [17]:

X = dataset.drop(['Name','Malware'], axis=1)
y = dataset['Malware']

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=101)
X_train.head()

e_magic  e_cblp  e_cp  e_crlc  e_cparhdr  e_minalloc  e_maxalloc  e_ss  \
11441    23117     144     3       0          4           0       65535     0   
2624     23117     144     3       0          4           0       65535     0   
18874    23117     144     3       0          4           0       65535     0   
16415    23117     144     3       0          4           0       65535     0   
11179    23117     144     3       0          4           0       65535     0   

       e_sp  e_csum  ...  SectionMaxChar  SectionMainChar  \
11441   184       0  ...      3791650912                0   
2624    184       0  ...      3221225536                0   
18874   184       0  ...      3221225536                0   
16415   184       0  ...      3221225600                0   
11179   184       0  ...      3221225536                0   

       DirectoryEntryImport  DirectoryEntryImportSize  DirectoryEntryExport  \
11441                    17                        22                     0   
2624                      1                       135                     0   
18874                    15                       347                     4   
16415                     7                       159                     0   
11179                     4                        88                     0   

       ImageDirectoryEntryExport  ImageDirectoryEntryImport  \
11441                     409626                     422944   
2624                           0                     113332   
18874                     111632                     132520   
16415                          0                      29736   
11179                          0                     222988   

       ImageDirectoryEntryResource  ImageDirectoryEntryException  \
11441                        81920                         77824   
2624                        131072                             0   
18874                       139264                             0   
16415                       241664                             0   
11179                       241664                             0   

       ImageDirectoryEntrySecurity  
11441                            0  
2624                             0  
18874                            0  
16415                    117181216  
11179                       719360  

[5 rows x 77 columns]

In [18]:

dataset.drop(['Name','Malware'], axis=1).values

array([[2.31170e+04, 1.44000e+02, 3.00000e+00, ..., 7.78240e+04,
        7.37280e+04, 0.00000e+00],
       [2.31170e+04, 1.44000e+02, 3.00000e+00, ..., 2.94912e+05,
        0.00000e+00, 3.46112e+05],
       [2.31170e+04, 1.44000e+02, 3.00000e+00, ..., 4.09600e+04,
        0.00000e+00, 0.00000e+00],
       ...,
       [2.31170e+04, 0.00000e+00, 0.00000e+00, ..., 6.14400e+04,
        0.00000e+00, 0.00000e+00],
       [2.31170e+04, 1.44000e+02, 3.00000e+00, ..., 1.02400e+05,
        0.00000e+00, 0.00000e+00],
       [2.31170e+04, 1.44000e+02, 3.00000e+00, ..., 5.57056e+05,
        0.00000e+00, 0.00000e+00]])

In [19]:

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)

D:\Others\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Others\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [20]:
X_new = pd.DataFrame(X_scaled, columns=X.columns)
X_new.head()

e_magic    e_cblp      e_cp    e_crlc  e_cparhdr  e_minalloc  e_maxalloc  \
0      0.0 -0.038591 -0.050297 -0.041557  -0.040212   -0.042419    0.148298   
1      0.0 -0.038591 -0.050297 -0.041557  -0.040212   -0.042419    0.148298   
2      0.0 -0.038591 -0.050297 -0.041557  -0.040212   -0.042419    0.148298   
3      0.0 -0.038591 -0.050297 -0.041557  -0.040212   -0.042419    0.148298   
4      0.0 -0.038591 -0.050297 -0.041557  -0.040212   -0.042419    0.148298   

       e_ss      e_sp    e_csum  ...  SectionMaxChar  SectionMainChar  \
0 -0.016139 -0.036843 -0.031918  ...        1.076024              0.0   
1 -0.016139 -0.036843 -0.031918  ...        0.097299              0.0   
2 -0.016139 -0.036843 -0.031918  ...        0.097299              0.0   
3 -0.016139 -0.036843 -0.031918  ...        0.097299              0.0   
4 -0.016139 -0.036843 -0.031918  ...        0.097299              0.0   

   DirectoryEntryImport  DirectoryEntryImportSize  DirectoryEntryExport  \
0              1.379922                 -0.623512             -0.087645   
1             -0.656755                  0.249356             -0.087645   
2              1.125337                  1.886949             -0.063126   
3              0.106999                  0.434744             -0.087645   
4             -0.274878                 -0.113695             -0.087645   

   ImageDirectoryEntryExport  ImageDirectoryEntryImport  \
0                   0.000436                  -0.000677   
1                  -0.016366                  -0.059942   
2                  -0.011787                  -0.056269   
3                  -0.016366                  -0.075943   
4                  -0.016366                  -0.038952   

   ImageDirectoryEntryResource  ImageDirectoryEntryException  \
0                    -0.067061                     -0.019125   
1                    -0.060538                     -0.020494   
2                    -0.059451                     -0.020494   
3                    -0.045862                     -0.020494   
4                    -0.045862                     -0.020494   

   ImageDirectoryEntrySecurity  
0                    -0.040622  
1                    -0.040622  
2                    -0.040622  
3                     5.561297  
4                    -0.006233  

[5 rows x 77 columns]

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
print("Test Score: {:.2f}".format(knn.score(X_test,y_test)))

Test Score: 0.99


In [24]:
d2 = pd.read_csv('dataset_test.csv')
d2.head()

Name  e_magic  e_cblp  e_cp  e_crlc  e_cparhdr  e_minalloc  \
0    Skype-8.10.0.9.exe    23117      80     2       0          4          15   
1   vlc-3.0.2-win64.exe    23117     144     3       0          4           0   
2         stinger32.exe    23117      64     1       0          2           0   
3  SpotifyFullSetup.exe    23117     144     3       0          4           0   
4      uftp_english.exe    23117     144     3       0          4           0   

   e_maxalloc  e_ss  e_sp  ...  SectionMaxChar  SectionMainChar  \
0       65535     0   184  ...      3221225536                0   
1       65535     0   184  ...      3227517056                0   
2       65535     0   184  ...      3758096608                0   
3       65535     0   184  ...      3221225536                0   
4       65535     0   184  ...      3221225536                0   

   DirectoryEntryImport  DirectoryEntryImportSize  DirectoryEntryExport  \
0                    11                       122                     0   
1                     7                       165                     0   
2                     1                         2                     7   
3                     8                       159                     0   
4                     4                        92                     0   

   ImageDirectoryEntryExport  ImageDirectoryEntryImport  \
0                          0                     102400   
1                          0                     208896   
2                   36339712                   36339976   
3                          0                     634448   
4                          0                      38620   

   ImageDirectoryEntryResource  ImageDirectoryEntryException  \
0                       114688                             0   
1                       430080                             0   
2                     36343808                             0   
3                       679936                             0   
4                        49152                             0   

   ImageDirectoryEntrySecurity  
0                     53905336  
1                     40201272  
2                     16478208  
3                     63220064  
4                     35544576  

[5 rows x 78 columns]

In [30]:
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
mal_encoded=le.fit_transform(y)
print(mal_encoded)


[1 1 1 ... 0 0 0]


In [34]:
model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X,y)
J_test=d2.drop(['Name'], axis=1)
predicted= knn.predict(J_test) 
print(predicted)

[0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0]
